stages:
  - install
  - build
  - test
  - code-quality

variables:
  RULES_CHANGES_PATH: "**/*"
  SONAR_TOKEN: ""

# Only runs the stages on things that have changes, unless on master branch. Saves computing power and time.
.base-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $RULES_CHANGES_PATH
    - when: manual
      allow_failure: true

# Sets the directory for the backend and grabs the correct image
.backend:
  extends: .base-rules
  image: gradle:7.1.1-jdk11
  variables:
    RULES_CHANGES_PATH: "backend/**/*"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - SONAR_TOKEN=${SONAR_BACKEND_TOKEN}
    - cd ./backend
    - cp -fr $application_properties_dev config/application.properties
    - export GRADLE_USER_HOME=`pwd`/.gradle

# Sets the directory for the frontend
.frontend:
  extends: .base-rules
  image: node:14.18.1
  variables:
    RULES_CHANGES_PATH: "frontend/knowl3dge-webapp/**/*"
  before_script:
    - SONAR_TOKEN=${SONAR_FRONTEND_TOKEN}
    - apt-get update
    - cd ./frontend/knowl3dge-webapp
    - npm install --legacy-peer-deps
  cache:
    key:
      files:
        - frontend/knowl3dge-webapp/package-lock.json
    paths:
      - frontend/knowl3dge-webapp/node_modules

frontend-install-dependencies:
  stage: install
  image: node:14.18.1
  script:
    - yarn install
    - yarn ngcc --properties es2015 --create-ivy-entry-points
  cache:
    key:
      files:
        - frontend/knowl3dge-webapp/yarn.lock
    paths:
      - frontend/knowl3dge-webapp/node_modules
  only:
    refs:
      - merge_requests
      - master
    changes:
      - frontend/knowl3dge-webapp/yarn.lock

backend-build:
  stage: build
  extends: .backend
  needs: []
  script:
    - echo "Compiling the backend code..."
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

frontend-build:
  stage: build
  extends: .frontend
  script:
    - yarn ng build --prod
  artifacts:
    name: "angular-app-pipeline"
    paths:
      - $APP_OUTPUT_PATH
  cache:
    key:
      files:
        - frontend/knowl3dge-webapp/yarn.lock
    paths:
      - frontend/knowl3dge-webapp/node_modules
    policy: pull

backend-test:
  stage: test
  extends: .backend
  needs: ["backend-build"]
  script:
    - echo "Testing the backend code..."
    - gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/test/TEST-*.xml

frontend-test:
  stage: test
  extends: .frontend
  script:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome

    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  cache:
    key:
      files:
        - frontend/knowl3dge-webapp/yarn.lock
    paths:
      - frontend/knowl3dge-webapp/node_modules
    policy: pull
  artifacts:
    paths:
      - frontend/knowl3dge-webapp/coverage
      - frontend/knowl3dge-webapp/reports
    reports:
      junit: frontend/knowl3dge-webapp/reports/junit_report.xml
    expire_in: 1 day

backend-code-quality:
  stage: code-quality
  extends: .backend
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: gradle sonarqube
  allow_failure: true

frontend-code-quality:
  stage: code-quality
  extends: .frontend
  needs: ["frontend-test"]
  dependencies:
    - frontend-test
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key:
      files:
        - frontend/knowl3dge-webapp/yarn.lock
    paths:
      - frontend/knowl3dge-webapp/node_modules
    policy: pull
  script:
    - npm run sonar-scanner -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_FRONTEND_TOKEN}
  allow_failure: true
